INSERT INTO COMPTE(ID, NOM, PRENOM,ACTIF,ID_ROLE) VALUES (1,'Yousra', 'HADJ MESSAOUD' , 1 , 1);
INSERT INTO COMPTE(ID, NOM, PRENOM,ACTIF,ID_ROLE) VALUES (2,'Jean Christophe', 'CHEVRIER' , 1 , 2);
INSERT INTO COMPTE(ID, NOM, PRENOM,ACTIF,ID_ROLE) VALUES (3,'Marième', 'LOUGADI' , 1 , 3);
INSERT INTO COMPTE(ID, NOM, PRENOM,ACTIF,ID_ROLE) VALUES (4,'Théo', 'DUPONT' , 1 , 4);
INSERT INTO COMPTE(ID, NOM, PRENOM,ACTIF,ID_ROLE) VALUES (5,'Christa', 'ANDERSON' , 1 , 5)
